sh ./src/process_one_sample_global.sh 1bkd_R 6
sh ./src/process_one_sample_global.sh 11as_AB 6
sh ./src/process_one_sample_global.sh 1eog_AB 6
sh ./src/process_one_sample_global.sh 1p7s_A 6
sh ./src/process_one_sample_global.sh 6wsk_A 6
sh ./src/process_one_sample_global.sh 1l14_A 6
sh ./src/process_one_sample_global.sh 1l15_A 6
sh ./src/process_one_sample_global.sh 1l16_A 6
sh ./src/process_one_sample_global.sh 1eoh_GH 6
sh ./src/process_one_sample_global.sh 2paw_A 6
sh ./src/process_one_sample_global.sh 4xh9_B 6
sh ./src/process_one_sample_global.sh 1ck0_HL 6
sh ./src/process_one_sample_global.sh 7n6t_AB 6
sh ./src/process_one_sample_global.sh 1pbn_A 6
sh ./src/process_one_sample_global.sh 1xgd_A 6
sh ./src/process_one_sample_global.sh 1hxf_HIL 6
sh ./src/process_one_sample_global.sh 5cha_EFG 6
sh ./src/process_one_sample_global.sh 1dla_B 6
sh ./src/process_one_sample_global.sh 1ahc_A 6
sh ./src/process_one_sample_global.sh 4f76_AB 6
sh ./src/process_one_sample_global.sh 1ah6_A 6
sh ./src/process_one_sample_global.sh 3c0e_A 6
sh ./src/process_one_sample_global.sh 5csc_A 6
sh ./src/process_one_sample_global.sh 1brb_E 6
sh ./src/process_one_sample_global.sh 1k9o_E 6
sh ./src/process_one_sample_global.sh 1brc_E 6
sh ./src/process_one_sample_global.sh 1yuw_A 6
sh ./src/process_one_sample_global.sh 1auv_AB 6
sh ./src/process_one_sample_global.sh 1tgn_A 6
sh ./src/process_one_sample_global.sh 1a4u_AB 6
sh ./src/process_one_sample_global.sh 5ano_A 6
sh ./src/process_one_sample_global.sh 6yl6_A 6
sh ./src/process_one_sample_global.sh 1bkn_B 6
sh ./src/process_one_sample_global.sh 1tsu_AB 6
sh ./src/process_one_sample_global.sh 4f74_AB 6
sh ./src/process_one_sample_global.sh 2nxm_AB 6
sh ./src/process_one_sample_global.sh 3nel_AB 6
sh ./src/process_one_sample_global.sh 1b8p_A 6
sh ./src/process_one_sample_global.sh 4kde_AB 6
sh ./src/process_one_sample_global.sh 2akp_A 6
sh ./src/process_one_sample_global.sh 6dwf_A 6
sh ./src/process_one_sample_global.sh 1ppe_E 6
sh ./src/process_one_sample_global.sh 1iz9_AB 6
sh ./src/process_one_sample_global.sh 4e5a_X 6
sh ./src/process_one_sample_global.sh 2cbe_A 6
sh ./src/process_one_sample_global.sh 1fqn_A 6
sh ./src/process_one_sample_global.sh 1fsn_A 6
sh ./src/process_one_sample_global.sh 1cvf_A 6
sh ./src/process_one_sample_global.sh 1hva_A 6
sh ./src/process_one_sample_global.sh 1zsa_A 6
sh ./src/process_one_sample_global.sh 1pdb_A 6
sh ./src/process_one_sample_global.sh 4pgm_ABCD 6
sh ./src/process_one_sample_global.sh 5ddz_A 6
sh ./src/process_one_sample_global.sh 1byi_A 6
sh ./src/process_one_sample_global.sh 1b8e_A 6
sh ./src/process_one_sample_global.sh 2iln_A 6
sh ./src/process_one_sample_global.sh 1d6r_A 6
sh ./src/process_one_sample_global.sh 1oph_B 6
sh ./src/process_one_sample_global.sh 4rnt_A 6
sh ./src/process_one_sample_global.sh 2nph_AB 6
sh ./src/process_one_sample_global.sh 1gfs_A 6
sh ./src/process_one_sample_global.sh 1beo_A 6
sh ./src/process_one_sample_global.sh 5j80_A 6
sh ./src/process_one_sample_global.sh 1oem_X 6
sh ./src/process_one_sample_global.sh 5cfz_AB 6
sh ./src/process_one_sample_global.sh 1tab_E 6
sh ./src/process_one_sample_global.sh 1ezx_C 6
sh ./src/process_one_sample_global.sh 2tld_E 6
sh ./src/process_one_sample_global.sh 2qn5_T 6
sh ./src/process_one_sample_global.sh 2bvv_A 6
sh ./src/process_one_sample_global.sh 7ken_A 6
sh ./src/process_one_sample_global.sh 7l0c_A 6
sh ./src/process_one_sample_global.sh 5ka4_A 6
sh ./src/process_one_sample_global.sh 4qbe_A 6
sh ./src/process_one_sample_global.sh 1mif_ABC 6
sh ./src/process_one_sample_global.sh 3d95_A 6
sh ./src/process_one_sample_global.sh 1ade_A 6
sh ./src/process_one_sample_global.sh 1adi_A 6
sh ./src/process_one_sample_global.sh 1u0v_A 6
sh ./src/process_one_sample_global.sh 1mjm_AB 6
sh ./src/process_one_sample_global.sh 2fbp_A 6
sh ./src/process_one_sample_global.sh 1chq_DEFGH 6
sh ./src/process_one_sample_global.sh 7icd_A 6
sh ./src/process_one_sample_global.sh 1ecl_A 6
sh ./src/process_one_sample_global.sh 2y0r_X 6
sh ./src/process_one_sample_global.sh 7jul_A 6
sh ./src/process_one_sample_global.sh 2fhs_AB 6
sh ./src/process_one_sample_global.sh 1dts_A 6
sh ./src/process_one_sample_global.sh 5loc_AB 6
sh ./src/process_one_sample_global.sh 1elo_A 6
sh ./src/process_one_sample_global.sh 1jam_A 6
sh ./src/process_one_sample_global.sh 1bbc_A 6
sh ./src/process_one_sample_global.sh 1dc5_AB 6
sh ./src/process_one_sample_global.sh 1tjv_ABCD 6
sh ./src/process_one_sample_global.sh 1dd3_ABCD 6
sh ./src/process_one_sample_global.sh 1lio_A 6
sh ./src/process_one_sample_global.sh 1bhs_A 6
sh ./src/process_one_sample_global.sh 1hcl_A 6
sh ./src/process_one_sample_global.sh 1dsu_A 6
sh ./src/process_one_sample_global.sh 2sil_A 6
sh ./src/process_one_sample_global.sh 1dkl_A 6
sh ./src/process_one_sample_global.sh 2wl6_ABCD 6
sh ./src/process_one_sample_global.sh 1pw2_A 6
sh ./src/process_one_sample_global.sh 1xcg_B 6
sh ./src/process_one_sample_global.sh 1hm5_AB 6
sh ./src/process_one_sample_global.sh 4eiz_A 6
sh ./src/process_one_sample_global.sh 1crw_GR 6
sh ./src/process_one_sample_global.sh 4ae0_A 6
sh ./src/process_one_sample_global.sh 1sua_A 6
sh ./src/process_one_sample_global.sh 1a3y_AB 6
sh ./src/process_one_sample_global.sh 1lyl_A 6
sh ./src/process_one_sample_global.sh 1buh_A 6
sh ./src/process_one_sample_global.sh 5if1_A 6
sh ./src/process_one_sample_global.sh 1bga_A 6
sh ./src/process_one_sample_global.sh 1w28_A 6
sh ./src/process_one_sample_global.sh 1pyp_AB 6
sh ./src/process_one_sample_global.sh 1e15_AB 6
sh ./src/process_one_sample_global.sh 1e8f_AB 6
sh ./src/process_one_sample_global.sh 1e8y_A 6
sh ./src/process_one_sample_global.sh 1vf8_A 6
sh ./src/process_one_sample_global.sh 1fle_E 6
sh ./src/process_one_sample_global.sh 1eaw_A 6
sh ./src/process_one_sample_global.sh 1e89_AB 6
sh ./src/process_one_sample_global.sh 3zv2_A 6
sh ./src/process_one_sample_global.sh 2cv3_A 6
sh ./src/process_one_sample_global.sh 1eai_A 6
sh ./src/process_one_sample_global.sh 3hhp_A 6
sh ./src/process_one_sample_global.sh 5rdh_A 6
sh ./src/process_one_sample_global.sh 2ied_A 6
sh ./src/process_one_sample_global.sh 1kf7_A 6
sh ./src/process_one_sample_global.sh 1epa_AB 6
sh ./src/process_one_sample_global.sh 5r32_A 6
sh ./src/process_one_sample_global.sh 5r35_A 6
sh ./src/process_one_sample_global.sh 1hbq_A 6
sh ./src/process_one_sample_global.sh 1yt4_A 6
sh ./src/process_one_sample_global.sh 1zg4_A 6
sh ./src/process_one_sample_global.sh 1cwy_A 6
sh ./src/process_one_sample_global.sh 1mkx_HK 6
sh ./src/process_one_sample_global.sh 1mkw_HL 6
sh ./src/process_one_sample_global.sh 1ycp_HL 6
sh ./src/process_one_sample_global.sh 1qid_A 6
sh ./src/process_one_sample_global.sh 1ex6_A 6
sh ./src/process_one_sample_global.sh 1hka_A 6
sh ./src/process_one_sample_global.sh 2exo_A 6
sh ./src/process_one_sample_global.sh 1ezi_AB 6
sh ./src/process_one_sample_global.sh 1c5m_DF 6
sh ./src/process_one_sample_global.sh 1c8o_AB 6
sh ./src/process_one_sample_global.sh 1hcg_AB 6
sh ./src/process_one_sample_global.sh 1f14_AB 6
sh ./src/process_one_sample_global.sh 1arl_A 6
sh ./src/process_one_sample_global.sh 3m61_U 6
sh ./src/process_one_sample_global.sh 1dg3_A 6
sh ./src/process_one_sample_global.sh 1f5z_ABCD 6
sh ./src/process_one_sample_global.sh 1f7o_ABC 6
sh ./src/process_one_sample_global.sh 1f8x_AB 6
sh ./src/process_one_sample_global.sh 1n7o_A 6
sh ./src/process_one_sample_global.sh 3kug_A 6
sh ./src/process_one_sample_global.sh 2bls_AB 6
sh ./src/process_one_sample_global.sh 1x6l_A 6
sh ./src/process_one_sample_global.sh 2gcb_A 6
sh ./src/process_one_sample_global.sh 1fhu_A 6
sh ./src/process_one_sample_global.sh 1mzl_A 6
sh ./src/process_one_sample_global.sh 1fjh_AB 6
sh ./src/process_one_sample_global.sh 1fo9_A 6
sh ./src/process_one_sample_global.sh 1mh3_A 6
sh ./src/process_one_sample_global.sh 1mh4_A 6
sh ./src/process_one_sample_global.sh 5hvi_A 6
sh ./src/process_one_sample_global.sh 1ftf_ABC 6
sh ./src/process_one_sample_global.sh 1lb1_B 6
sh ./src/process_one_sample_global.sh 1fva_B 6
sh ./src/process_one_sample_global.sh 5uq2_A 6
sh ./src/process_one_sample_global.sh 2i3w_A 6
sh ./src/process_one_sample_global.sh 1g1u_ABCD 6
sh ./src/process_one_sample_global.sh 2pt7_AB 6
sh ./src/process_one_sample_global.sh 1lib_A 6
sh ./src/process_one_sample_global.sh 1g7r_A 6
sh ./src/process_one_sample_global.sh 1x8f_A 6
sh ./src/process_one_sample_global.sh 1fg5_N 6
sh ./src/process_one_sample_global.sh 1g95_A 6
sh ./src/process_one_sample_global.sh 1n8t_AB 6
sh ./src/process_one_sample_global.sh 5vmr_A 6
sh ./src/process_one_sample_global.sh 1z0h_A 6
sh ./src/process_one_sample_global.sh 2nm1_A 6
sh ./src/process_one_sample_global.sh 6uht_A 6
sh ./src/process_one_sample_global.sh 1g0s_AB 6
sh ./src/process_one_sample_global.sh 1dc3_AB 6
sh ./src/process_one_sample_global.sh 1hkl_HL 6
sh ./src/process_one_sample_global.sh 4cha_F 6
sh ./src/process_one_sample_global.sh 2hnp_A 6
sh ./src/process_one_sample_global.sh 7jrx_ABC 6
sh ./src/process_one_sample_global.sh 1dja_A 6
sh ./src/process_one_sample_global.sh 2jdl_A 6
sh ./src/process_one_sample_global.sh 1gis_A 6
sh ./src/process_one_sample_global.sh 1bay_AB 6
sh ./src/process_one_sample_global.sh 2gch_EFG 6
sh ./src/process_one_sample_global.sh 1qie_A 6
sh ./src/process_one_sample_global.sh 1qif_A 6
sh ./src/process_one_sample_global.sh 3rgr_A 6
sh ./src/process_one_sample_global.sh 1gsh_A 6
sh ./src/process_one_sample_global.sh 3q74_AB 6
sh ./src/process_one_sample_global.sh 5r33_A 6
sh ./src/process_one_sample_global.sh 4q13_ABCD 6
sh ./src/process_one_sample_global.sh 1uz2_X 6
sh ./src/process_one_sample_global.sh 1qg5_A 6
sh ./src/process_one_sample_global.sh 1gyj_AB 6
sh ./src/process_one_sample_global.sh 1a3h_A 6
sh ./src/process_one_sample_global.sh 1qhm_AB 6
sh ./src/process_one_sample_global.sh 1qig_A 6
sh ./src/process_one_sample_global.sh 1qih_A 6
sh ./src/process_one_sample_global.sh 1vgt_AB 6
sh ./src/process_one_sample_global.sh 1hxj_AB 6
sh ./src/process_one_sample_global.sh 5c67_A 6
sh ./src/process_one_sample_global.sh 5eop_A 6
sh ./src/process_one_sample_global.sh 5k2q_A 6
sh ./src/process_one_sample_global.sh 1fwl_A 6
sh ./src/process_one_sample_global.sh 1h7e_AB 6
sh ./src/process_one_sample_global.sh 1h6j_AB 6
sh ./src/process_one_sample_global.sh 1qii_A 6
sh ./src/process_one_sample_global.sh 5i48_ABCD 6
sh ./src/process_one_sample_global.sh 2hpe_AB 6
sh ./src/process_one_sample_global.sh 1a30_AB 6
sh ./src/process_one_sample_global.sh 3rsw_A 6
sh ./src/process_one_sample_global.sh 1hnk_A 6
sh ./src/process_one_sample_global.sh 5im1_A 6
sh ./src/process_one_sample_global.sh 5ilk_A 6
sh ./src/process_one_sample_global.sh 1zyn_A 6
sh ./src/process_one_sample_global.sh 2ahb_AB 6
sh ./src/process_one_sample_global.sh 5wrn_CD 6
sh ./src/process_one_sample_global.sh 1i39_A 6
sh ./src/process_one_sample_global.sh 1p14_A 6
sh ./src/process_one_sample_global.sh 1vgu_A 6
sh ./src/process_one_sample_global.sh 1mjy_A 6
sh ./src/process_one_sample_global.sh 6l8b_AB 6
sh ./src/process_one_sample_global.sh 1i7n_AB 6
sh ./src/process_one_sample_global.sh 2hpf_AB 6
sh ./src/process_one_sample_global.sh 1idd_A 6
sh ./src/process_one_sample_global.sh 1gke_ABCD 6
sh ./src/process_one_sample_global.sh 1ift_A 6
sh ./src/process_one_sample_global.sh 1obs_A 6
sh ./src/process_one_sample_global.sh 1jks_A 6
sh ./src/process_one_sample_global.sh 1is5_A 6
sh ./src/process_one_sample_global.sh 1idf_A 6
sh ./src/process_one_sample_global.sh 1xyf_AB 6
sh ./src/process_one_sample_global.sh 6c78_A 6
sh ./src/process_one_sample_global.sh 2wyx_A 6
sh ./src/process_one_sample_global.sh 2xqz_A 6
sh ./src/process_one_sample_global.sh 3ndd_A 6
sh ./src/process_one_sample_global.sh 5dti_AB 6
sh ./src/process_one_sample_global.sh 2cuz_A 6
sh ./src/process_one_sample_global.sh 1x1h_A 6
sh ./src/process_one_sample_global.sh 1bk7_A 6
sh ./src/process_one_sample_global.sh 1irm_C 6
sh ./src/process_one_sample_global.sh 1bgt_A 6
sh ./src/process_one_sample_global.sh 2gca_A 6
sh ./src/process_one_sample_global.sh 1ktn_AB 6
sh ./src/process_one_sample_global.sh 2jdw_A 6
sh ./src/process_one_sample_global.sh 1kxv_A 6
sh ./src/process_one_sample_global.sh 2bgt_A 6
sh ./src/process_one_sample_global.sh 1jej_A 6
sh ./src/process_one_sample_global.sh 1jgv_HL 6
sh ./src/process_one_sample_global.sh 1p1f_AB 6
sh ./src/process_one_sample_global.sh 3dgk_A 6
sh ./src/process_one_sample_global.sh 6fha_A 6
sh ./src/process_one_sample_global.sh 1bo7_A 6
sh ./src/process_one_sample_global.sh 4h39_A 6
sh ./src/process_one_sample_global.sh 3qas_AB 6
sh ./src/process_one_sample_global.sh 1inl_ABCD 6
sh ./src/process_one_sample_global.sh 1fiy_A 6
sh ./src/process_one_sample_global.sh 1hfw_ABCD 6
sh ./src/process_one_sample_global.sh 5i3z_ABCD 6
sh ./src/process_one_sample_global.sh 1l7r_A 6
sh ./src/process_one_sample_global.sh 2b5r_A 6
sh ./src/process_one_sample_global.sh 1fm2_AB 6
sh ./src/process_one_sample_global.sh 2hnt_F 6
sh ./src/process_one_sample_global.sh 5i52_A 6
sh ./src/process_one_sample_global.sh 5kkf_A 6
sh ./src/process_one_sample_global.sh 1hqo_AB 6
sh ./src/process_one_sample_global.sh 1acb_E 6
sh ./src/process_one_sample_global.sh 1k3o_AB 6
sh ./src/process_one_sample_global.sh 1xwg_AB 6
sh ./src/process_one_sample_global.sh 3ou4_AB 6
sh ./src/process_one_sample_global.sh 3oub_AB 6
sh ./src/process_one_sample_global.sh 7l5v_AB 6
sh ./src/process_one_sample_global.sh 3ots_AB 6
sh ./src/process_one_sample_global.sh 3ou3_AB 6
sh ./src/process_one_sample_global.sh 1tju_ABCD 6
sh ./src/process_one_sample_global.sh 1ecp_ABCDEF 6
sh ./src/process_one_sample_global.sh 3g1s_A 6
sh ./src/process_one_sample_global.sh 3m5x_AB 6
sh ./src/process_one_sample_global.sh 3g1d_A 6
sh ./src/process_one_sample_global.sh 3g22_A 6
sh ./src/process_one_sample_global.sh 3g18_A 6
sh ./src/process_one_sample_global.sh 1dv7_A 6
sh ./src/process_one_sample_global.sh 3t06_B 6
sh ./src/process_one_sample_global.sh 1chu_A 6
sh ./src/process_one_sample_global.sh 1prg_AB 6
sh ./src/process_one_sample_global.sh 1kan_AB 6
sh ./src/process_one_sample_global.sh 1kpa_AB 6
sh ./src/process_one_sample_global.sh 1kpb_A 6
sh ./src/process_one_sample_global.sh 5vet_AB 6
sh ./src/process_one_sample_global.sh 1o24_ABCD 6
sh ./src/process_one_sample_global.sh 1kqx_A 6
sh ./src/process_one_sample_global.sh 1ksv_A 6
sh ./src/process_one_sample_global.sh 2y8o_A 6
sh ./src/process_one_sample_global.sh 3q37_CD 6
sh ./src/process_one_sample_global.sh 1kwb_B 6
sh ./src/process_one_sample_global.sh 1kz1_ABCDE 6
sh ./src/process_one_sample_global.sh 1gvl_A 6
sh ./src/process_one_sample_global.sh 2g67_AB 6
sh ./src/process_one_sample_global.sh 1lbv_AB 6
sh ./src/process_one_sample_global.sh 1lbw_AB 6
sh ./src/process_one_sample_global.sh 1swh_CD 6
sh ./src/process_one_sample_global.sh 1ceq_A 6
sh ./src/process_one_sample_global.sh 1rav_AB 6
sh ./src/process_one_sample_global.sh 1lf4_A 6
sh ./src/process_one_sample_global.sh 3f9q_A 6
sh ./src/process_one_sample_global.sh 1l17_A 6
sh ./src/process_one_sample_global.sh 1l18_A 6
sh ./src/process_one_sample_global.sh 1l19_A 6
sh ./src/process_one_sample_global.sh 1ab0_A 6
sh ./src/process_one_sample_global.sh 1alb_A 6
sh ./src/process_one_sample_global.sh 5c0n_A 6
sh ./src/process_one_sample_global.sh 135l_A 6
sh ./src/process_one_sample_global.sh 1gif_ABC 6
sh ./src/process_one_sample_global.sh 2hvm_A 6
sh ./src/process_one_sample_global.sh 1lmn_A 6
sh ./src/process_one_sample_global.sh 5nx1_A 6
sh ./src/process_one_sample_global.sh 1gbs_A 6
sh ./src/process_one_sample_global.sh 1htl_DEFGH 6
sh ./src/process_one_sample_global.sh 1lu9_ABC 6
sh ./src/process_one_sample_global.sh 2vff_A 6
sh ./src/process_one_sample_global.sh 6bjj_A 6
sh ./src/process_one_sample_global.sh 3ctb_A 6
sh ./src/process_one_sample_global.sh 1s2t_AB 6
sh ./src/process_one_sample_global.sh 6apa_A 6
sh ./src/process_one_sample_global.sh 5lqb_A 6
sh ./src/process_one_sample_global.sh 1pz5_AB 6
sh ./src/process_one_sample_global.sh 1vga_CD 6
sh ./src/process_one_sample_global.sh 2okr_A 6
sh ./src/process_one_sample_global.sh 7ek8_ABCD 6
sh ./src/process_one_sample_global.sh 2gdg_ABC 6
sh ./src/process_one_sample_global.sh 4yon_B 6
sh ./src/process_one_sample_global.sh 1hqq_AB 6
sh ./src/process_one_sample_global.sh 1mkb_AB 6
sh ./src/process_one_sample_global.sh 2bp2_A 6
sh ./src/process_one_sample_global.sh 2vf4_X 6
sh ./src/process_one_sample_global.sh 3pte_A 6
sh ./src/process_one_sample_global.sh 1mri_A 6
sh ./src/process_one_sample_global.sh 2vs6_B 6
sh ./src/process_one_sample_global.sh 2c0y_A 6
sh ./src/process_one_sample_global.sh 1muf_A 6
sh ./src/process_one_sample_global.sh 1gsb_AB 6
sh ./src/process_one_sample_global.sh 1mtz_A 6
sh ./src/process_one_sample_global.sh 1j85_A 6
sh ./src/process_one_sample_global.sh 1wcs_A 6
sh ./src/process_one_sample_global.sh 1y92_A 6
sh ./src/process_one_sample_global.sh 1kl3_ABCD 6
sh ./src/process_one_sample_global.sh 1h2v_CZ 6
sh ./src/process_one_sample_global.sh 1kl4_ABCD 6
sh ./src/process_one_sample_global.sh 1m4c_B 6
sh ./src/process_one_sample_global.sh 1leo_A 6
sh ./src/process_one_sample_global.sh 1kl5_ABCD 6
sh ./src/process_one_sample_global.sh 1ypi_AB 6
sh ./src/process_one_sample_global.sh 1l46_A 6
sh ./src/process_one_sample_global.sh 2nck_LR 6
sh ./src/process_one_sample_global.sh 7rnd_AC 6
sh ./src/process_one_sample_global.sh 4jqy_AB 6
sh ./src/process_one_sample_global.sh 5cf1_CD 6
sh ./src/process_one_sample_global.sh 4k14_A 6
sh ./src/process_one_sample_global.sh 3bbb_ABCDEF 6
sh ./src/process_one_sample_global.sh 5cf2_AB 6
sh ./src/process_one_sample_global.sh 3toi_B 6
sh ./src/process_one_sample_global.sh 4gku_A 6
sh ./src/process_one_sample_global.sh 3dtm_A 6
sh ./src/process_one_sample_global.sh 1ks2_AB 6
sh ./src/process_one_sample_global.sh 1o9z_A 6
sh ./src/process_one_sample_global.sh 1ock_AB 6
sh ./src/process_one_sample_global.sh 5r39_A 6
sh ./src/process_one_sample_global.sh 1ocv_A 6
sh ./src/process_one_sample_global.sh 1ojq_A 6
sh ./src/process_one_sample_global.sh 1onn_AB 6
sh ./src/process_one_sample_global.sh 3t0h_A 6
sh ./src/process_one_sample_global.sh 6hl0_A 6
sh ./src/process_one_sample_global.sh 4e5b_A 6
sh ./src/process_one_sample_global.sh 1wfc_A 6
sh ./src/process_one_sample_global.sh 5etf_A 6
sh ./src/process_one_sample_global.sh 5eta_A 6
sh ./src/process_one_sample_global.sh 1p5h_AB 6
sh ./src/process_one_sample_global.sh 1p74_B 6
sh ./src/process_one_sample_global.sh 1pb7_A 6
sh ./src/process_one_sample_global.sh 6uz6_A 6
sh ./src/process_one_sample_global.sh 2pfk_CD 6
sh ./src/process_one_sample_global.sh 1na7_A 6
sh ./src/process_one_sample_global.sh 7e75_A 6
sh ./src/process_one_sample_global.sh 4h3b_A 6
sh ./src/process_one_sample_global.sh 1q5u_XYZ 6
sh ./src/process_one_sample_global.sh 1iad_A 6
sh ./src/process_one_sample_global.sh 1qmi_AB 6
sh ./src/process_one_sample_global.sh 6gqz_A 6
sh ./src/process_one_sample_global.sh 1qso_ABCD 6
sh ./src/process_one_sample_global.sh 1qij_A 6
sh ./src/process_one_sample_global.sh 1eic_A 6
sh ./src/process_one_sample_global.sh 1eid_A 6
sh ./src/process_one_sample_global.sh 1eie_A 6
sh ./src/process_one_sample_global.sh 1fs3_A 6
sh ./src/process_one_sample_global.sh 1sry_AB 6
sh ./src/process_one_sample_global.sh 1hxl_AB 6
sh ./src/process_one_sample_global.sh 1swl_AB 6
sh ./src/process_one_sample_global.sh 1swc_AB 6
sh ./src/process_one_sample_global.sh 1hxz_AB 6
sh ./src/process_one_sample_global.sh 1sbt_A 6
sh ./src/process_one_sample_global.sh 1swb_ABCD 6
sh ./src/process_one_sample_global.sh 1kff_ABCD 6
sh ./src/process_one_sample_global.sh 1swq_ABCD 6
sh ./src/process_one_sample_global.sh 1swa_ABCD 6
sh ./src/process_one_sample_global.sh 1swo_ABCD 6
sh ./src/process_one_sample_global.sh 1n7y_ABCD 6
sh ./src/process_one_sample_global.sh 1hy2_CD 6
sh ./src/process_one_sample_global.sh 5iq8_A 6
sh ./src/process_one_sample_global.sh 1cpj_AB 6
sh ./src/process_one_sample_global.sh 4p61_AB 6
sh ./src/process_one_sample_global.sh 1tim_AB 6
sh ./src/process_one_sample_global.sh 1sq7_AB 6
sh ./src/process_one_sample_global.sh 5i3f_A 6
sh ./src/process_one_sample_global.sh 5i3g_A 6
sh ./src/process_one_sample_global.sh 1qq1_A 6
sh ./src/process_one_sample_global.sh 1tyv_A 6
sh ./src/process_one_sample_global.sh 1clw_A 6
sh ./src/process_one_sample_global.sh 1uaj_A 6
sh ./src/process_one_sample_global.sh 1j2w_ABCD 6
sh ./src/process_one_sample_global.sh 1ubv_A 6
sh ./src/process_one_sample_global.sh 1uc8_AB 6
sh ./src/process_one_sample_global.sh 1lau_E 6
sh ./src/process_one_sample_global.sh 1avg_HL 6
sh ./src/process_one_sample_global.sh 3n4i_A 6
sh ./src/process_one_sample_global.sh 1qik_A 6
sh ./src/process_one_sample_global.sh 5i7g_A 6
sh ./src/process_one_sample_global.sh 2gub_A 6
sh ./src/process_one_sample_global.sh 3kcj_A 6
sh ./src/process_one_sample_global.sh 3kbj_A 6
sh ./src/process_one_sample_global.sh 3xin_ABCD 6
sh ./src/process_one_sample_global.sh 1xla_AB 6
sh ./src/process_one_sample_global.sh 1bhj_AB 6
sh ./src/process_one_sample_global.sh 1agy_A 6
sh ./src/process_one_sample_global.sh 1cus_A 6
sh ./src/process_one_sample_global.sh 1cuj_A 6
sh ./src/process_one_sample_global.sh 1axt_HL 6
sh ./src/process_one_sample_global.sh 1uyl_A 6
sh ./src/process_one_sample_global.sh 1l45_A 6
sh ./src/process_one_sample_global.sh 1l22_A 6
sh ./src/process_one_sample_global.sh 1ors_AB 6
sh ./src/process_one_sample_global.sh 1qim_A 6
sh ./src/process_one_sample_global.sh 3i17_A 6
sh ./src/process_one_sample_global.sh 1aat_AB 6
sh ./src/process_one_sample_global.sh 1xzh_A 6
sh ./src/process_one_sample_global.sh 4eug_A 6
sh ./src/process_one_sample_global.sh 1fgk_AB 6
sh ./src/process_one_sample_global.sh 1gsc_AB 6
sh ./src/process_one_sample_global.sh 4jo6_CD 6
sh ./src/process_one_sample_global.sh 1swf_AB 6
sh ./src/process_one_sample_global.sh 1pts_AB 6
sh ./src/process_one_sample_global.sh 5n7x_A 6
sh ./src/process_one_sample_global.sh 1swj_B 6
sh ./src/process_one_sample_global.sh 1sws_B 6
sh ./src/process_one_sample_global.sh 2iwm_ABCD 6
sh ./src/process_one_sample_global.sh 1sll_A 6
sh ./src/process_one_sample_global.sh 4f59_A 6
sh ./src/process_one_sample_global.sh 1idp_A 6
sh ./src/process_one_sample_global.sh 3fk6_A 6
sh ./src/process_one_sample_global.sh 7xim_ABCD 6
sh ./src/process_one_sample_global.sh 3fa8_A 6
sh ./src/process_one_sample_global.sh 4s31_A 6
sh ./src/process_one_sample_global.sh 1bkz_AB 6
sh ./src/process_one_sample_global.sh 1kiv_A 6
sh ./src/process_one_sample_global.sh 3o1z_A 6
sh ./src/process_one_sample_global.sh 1ca0_FGH 6
sh ./src/process_one_sample_global.sh 5r31_A 6
sh ./src/process_one_sample_global.sh 4s2z_A 6
sh ./src/process_one_sample_global.sh 1gmc_EFG 6
sh ./src/process_one_sample_global.sh 4i36_B 6
sh ./src/process_one_sample_global.sh 6rhn_A 6
sh ./src/process_one_sample_global.sh 1ymn_A 6
sh ./src/process_one_sample_global.sh 1hja_ABC 6
sh ./src/process_one_sample_global.sh 1eug_A 6
sh ./src/process_one_sample_global.sh 4fit_A 6
sh ./src/process_one_sample_global.sh 1ey0_A 6
sh ./src/process_one_sample_global.sh 1zah_ABCD 6
sh ./src/process_one_sample_global.sh 8jdw_A 6
sh ./src/process_one_sample_global.sh 2j24_AB 6
sh ./src/process_one_sample_global.sh 4jdw_A 6
sh ./src/process_one_sample_global.sh 4kkg_A 6
